# Generated by Django 4.0.3 on 2022-03-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bug',
            options={'verbose_name': 'bug管理', 'verbose_name_plural': 'bug管理'},
        ),
        migrations.AlterField(
            model_name='bug',
            name='buglevel',
            field=models.CharField(choices=[('紧急', '紧急'), ('严重', '严重'), ('一般', '一般')], default='一般', max_length=200, null=True, verbose_name='严重程度'),
        ),
    ]
